### PR TITLE
Remove reference to .codecov.yml in help section

### PR DESCRIPTION
**Pull request by joshua0308**
## Purpose
The docs on codecov.io advise users to name the config file as `codecov.yml` instead of `.codecov.yml`. However, upon reading through the bash script, I found reference to `.codecov.yml` in the help section for `-y` option. This can cause confusion for users referring to the help section of the bash script.

## Notable Changes
Update description. Change from `.codecov.yml` to `codecov.yml`.

### CODE REVIEW

**Comment by thomasrockhu** [comment]
Please update the SHA and I'll merge in

**Comment by thomasrockhu** [comment]
and thank you for the PR 😄

**Comment by joshua0308** [comment]
@thomasrockhu You're welcome! I'm still struggling to get this feature to work though. It would be great if you can take a look and direct me in the right way. The current repo structure at my work requires the `-y flag` to work as intended. 

I [opened an issue](https://community.codecov.io/t/option-y-in-bash-script-not-working-as-intended/1279) in the community forum a few weeks ago. The project mentioned in the ticket is my pet project. I wanted to test it out in a basic setup. I can also share the repo structure we have at work if that helps. Thanks!

**Comment by thomasrockhu** [comment]
Hi @joshua0308 I made a mistake here and pulled in https://github.com/codecov/codecov-bash/commit/7961ae4777eb5f3991f6e47d9f98b087918b2bd1 which removed the `.codecov.yml` reference. Closing this PR because it accomplishes the same.

Again, thanks for the PR, I always really appreciate help from the community. I'll respond to the community ticket shortly.

**Pull request closed without merging**
