### PR TITLE
Updates for more configurable gcov usage

### PR DESCRIPTION
**Pull request by lefticus**
* Make sure gcov is only called once
 * Allow passing of args to gcov
 * Allow configuration of gcov executable

### CODE REVIEW

**Comment by lefticus** [comment]
@stevepeak this gives me the configurability I need, and the results look great: https://codecov.io/github/ChaiScript/ChaiScript?branch=no_raw_loops

And the usage is straightforward: https://github.com/ChaiScript/ChaiScript/blob/6c7d718a9b227d8f021988a76aa3364414dcc93f/.travis.yml#L27

**Comment by stevepeak** [comment]
Could you try the build using master branch at:

```diff
- - if [ ${COVERAGE} = 1 ]; then bash <(curl -s https://raw.githubusercontent.com/lefticus/codecov-bash/wip/codecov) -x $GCOV -a "-s `pwd`" ; fi
+ - if [ ${COVERAGE} = 1 ]; then bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/master/codecov) -x $GCOV -a "-s `pwd`" ; fi
``` 

Thanks!

**Comment by lefticus** [comment]
@stevepeak looks good after the change.

**Comment by stevepeak** [comment]
Great! I'll be publishing this new version shortly.

**Comment by lefticus** [comment]
Let me know, I'll move to the official release when you get it updated

**Pull request merged**
