### PR TITLE
Fix gcov command

### PR DESCRIPTION
**Pull request by AenBleidd**
This pull request fixes gcov execution on linux.
Current behavior skips almost all *.gcda files.

Signed-off-by: Vitalii Koshura <lestat.de.lionkur@gmail.com>

### CODE REVIEW

**Comment by drazisil** [comment]
@hootener , @thomasrockhu

**Comment by AenBleidd** [comment]
I made rebase to fix the conflict. For some reason sha check is failed but locally these hashes match. Might be some CI issue

**Comment by AenBleidd** [comment]
@drazisil, @hootener, @thomasrockhu, could you please review this PR? It contains a fix for the bloker we have. Thanks in advance

**Comment by AenBleidd** [comment]
@drazisil, @hootener, @thomasrockhu, ping

**Comment by thomasrockhu** [comment]
Thanks @AenBleidd , this looks good to me. I'll push up a fix later today for the `SHA1SUM` and get this merged in

**Pull request merged**
