### PR TITLE
Use shunit2 from Travis/Ubuntu xenial

### PR DESCRIPTION
**Pull request by szepeviktor**
https://packages.ubuntu.com/xenial/shunit2

### CODE REVIEW

**Comment by szepeviktor** [comment]
All 🍏 :) :)

**Comment by szepeviktor** [comment]
@drazisil Could give this one a click too?

**Comment by drazisil** [comment]
@szepeviktor  Can you pin the version so I don't have to worry about changes possibly breaking things?

**Comment by szepeviktor** [comment]
In Debian there is one version per release.
But all five release of Ubuntu has the same version, see the youngest: https://packages.ubuntu.com/focal/shunit2

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
