### PR TITLE
[CE-1057] Add prow ci support

### PR DESCRIPTION
**Pull request by charlesakalugwu**
This adds support for detecting codecov jobs which are run on Prow CI.

Prow is the system used for building and testing the Kubernetes project.

```release-note
Add prow CI support
```

### CODE REVIEW

**Comment by G6JACX** [comment]
Approved

**Comment by charlesakalugwu** [comment]
@G6JACX thanks for approving this PR. There are several issues I would like to clear up with you however.

* In the case of a codecov job for a PR, what values should be set for commit and branch (-C and -B flags)? 
* Should the commit for a PR be set (-C) to the pull request head's sha or the base branch's sha (e.g. master for PR into master)?
* Should the branch for a PR be set (-B) to the base branch's sha or the github PR ref (e.g. pull/1269). It seems the travis CI integration uses the pull/1269 form.
* Since prow treats PR jobs separately from non-PR jobs (presubmit vs postsubmit jobs), I would need to make changes here https://github.com/codecov/codecov-bash/pull/168/commits/d15746da4cb97c32ef001d04f1a76ea44ed92236#diff-45b1150df0237fb1cb2a238a2d04554eR738 in order to conditionally set various values based on job type.
* The CI testing for this project is broken. I took a first stab at fixing them but probably need to dig deeper. I am inclined to take out those commits from this PR and possibly open a separate PR with only CI test fixes. What do you think?
* (Not necessary for this PR): Are you folks considering rewriting this bash uploader using something like golang?

**Comment by drazisil** [comment]
Hi @charlesakalugwu 

Thank you for the PR and my apologies in the delay in reviewing it. Before this is fully supported, I need to add it to the CI whitelist on the backend.

Can you you provide what a Prow CI build URL would look like?

If you are aware if Prow CI has a logo anywhere that would be helpful as well.

**Comment by thomasrockhu** [comment]
Closing out due to inactivity. @charlesakalugwu if you are able to provide the above from @drazisil's comment, please re-open.

**Pull request closed without merging**
