### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by fkorotkov**
by fixing test data

### CODE REVIEW

**Comment by fkorotkov** [comment]
There are 3 failures left that I cannot understand 😿

**Comment by fkorotkov** [comment]
All failures are coming from `test_fixes`. Had another attempt to understand what's going on there but with no success. @stevepeak could you please take a look?

**Comment by blueyed** [comment]
https://github.com/codecov/codecov-bash/pull/180 has fixes for CI.

**Comment by drazisil** [comment]
> There are 3 failures left that I cannot understand crying_cat_face

@fkorotkov 

Looks like the test file did not account for whitespace. I'd already started fixing this before I was alerted to your PR, I'm sorry no one ever got back to you, I wanted to thank you for trying.

**Pull request merged**
