### PR TITLE
Adjust coverage for .swift files too

### LINKED ISSUE #272: Empty line removals don't work for Xcode and Swift on Linux
Here is one of my files on codecov: https://codecov.io/gh/Cyberbeni/TypedNotificationCenter/src/87289325976cdacb8d1a9a7aa7c540e4e55ca9c2/Sources/TypedNotificationCenter/Core/TypedNotificationCenter.swift
The github action that uploaded the coverage: https://github.com/Cyberbeni/TypedNotificationCenter/runs/471046396
The workflow for that action: https://github.com/Cyberbeni/TypedNotificationCenter/blob/1.5.1/.github/workflows/run_tests.yml

### PR DESCRIPTION
**Pull request by Cyberbeni**
## Purpose
Fixes #272 

## Notable Changes
Apply adjustments to .swift coverage, like mentioned in the documentation.

## Tests and Risks?
Not covered by tests in this repo, little to no risk as only 3 lines changed
Manually tested here: https://github.com/Cyberbeni/TypedNotificationCenter/runs/473050500
Coverage report: https://codecov.io/gh/Cyberbeni/TypedNotificationCenter/tree/9f973256bcddf320e1a35700f59bcea54e6fb553

## Update the SHA1SUM file

output of `shasum codecov` written in SHA1SUM file

### CODE REVIEW

**Comment by Cyberbeni** [comment]
Or is it still supposed to be fixed server side, as stated in this commit message? https://github.com/codecov/codecov-bash/commit/6eef2cb2dc5e36f27435b6da33a2c32d9cccc627

**Comment by drazisil** [comment]
Hi @Cyberbeni 

I _think_ this is supposed to be handled server-side, can you explain more about what you are seeing? I'm having trouble following, sorry.

**Comment by Cyberbeni** [comment]
@drazisil 
Latest merge commit on master with the unmodified codecov bash script:
https://codecov.io/gh/Cyberbeni/TypedNotificationCenter/src/87289325976cdacb8d1a9a7aa7c540e4e55ca9c2/Sources/TypedNotificationCenter/Core/TypedNotificationCenter.swift
Github workflow file: https://github.com/Cyberbeni/TypedNotificationCenter/blob/87289325976cdacb8d1a9a7aa7c540e4e55ca9c2/.github/workflows/run_tests.yml

Same code but with the codecov bash from the PR:
https://codecov.io/gh/Cyberbeni/TypedNotificationCenter/src/9f973256bcddf320e1a35700f59bcea54e6fb553/Sources/TypedNotificationCenter/Core/TypedNotificationCenter.swift

The original script leaves empty lines and closing brackets in the code coverage, one of those was even marked as not covered. Applying the same fixes as Objective C (as they are also in the same category in the documentation) removes empty lines and closing brackets from the coverage.

**Comment by drazisil** [comment]
@Cyberbeni 

Got it, thanks for explaining! Can you resolve the SHA1SUM conflict and I'll merge?

**Comment by drazisil** [comment]
Deployment requested.

**Comment by drazisil** [comment]
This has been deployed

**Pull request merged**
