### PR TITLE
fix gcovoutput option

### PR DESCRIPTION
**Pull request by junghans**
It seems the `-X gcovoutput` option doesn't do anything and I think it is due to this line:
```
bash -c "find $ddp -type f -name '*.gcda' $gcov_include $gcov_ignore -exec $gcov_exe -p $gcov_arg {} +" || true 2>/dev/null
```
the filtering happens for `true` instead of the `find`.

Mini-Reproducer:
```
$ bash -c "echo hello >&2" || true 2>/dev/null
```
has output, while
```
bash -c "echo hello >&2" 2>/dev/null  || true
```
does not.

### CODE REVIEW

**Comment by junghans** [comment]
ping @stevepeak

**Comment by lightmare** [comment]
Can this please be merged in?

Currently I'm working around the ineffectual "-X gcovout" option by putting the redirection into the "-x" option like `-x gcov >/dev/null 2>&1`. Which leads me to suggesting a modification.

```bash
# this PR, redirect on bash
bash -c "find ... -execdir $gcov_exe -pb $gcov_arg {} +" >/dev/null 2>&1 || true
```
  - If the command string constructed from all those variables is not valid bash syntax, the redirection will devour the parsing error message from bash.

```bash
# alternative A, redirect on find
bash -c "find ... -execdir $gcov_exe -pb $gcov_arg {} + >/dev/null 2>&1" || true
```
  - This way invalid bash syntax will produce an error message. But if the arguments to find are not valid find-expression, error message from find will get eaten.


```bash
# alternative B, redirect only command executed by find
shush="sh -c 'exec >/dev/null 2>&1 \"\$@\"' shush"
bash -c "find ... -execdir $shush $gcov_exe -pb $gcov_arg {} + " || true
```
  - This lets through syntax error messages from bash and find, and only suppresses the actual `gcov_exe` command's output.

And this `shush` variable can be moved up to reduce code duplication, so that you don't need to test `ft_gcovout` on individual invocations:
```bash
if [ "$ft_gcovout" = "0" ]; then
  shush="sh -c 'exec >/dev/null 2>&1 \"\$@\"' shush"
else
  shush=''
fi
```

**Comment by junghans** [comment]
ping @felipeball

**Comment by christophebedard** [comment]
Any updates on this?

**Comment by drazisil** [comment]
@junghans Can you please update the SHA1SUM file?

**Comment by junghans** [comment]
@drazisil done.

**Comment by drazisil** [comment]
Deployment requested.

**Comment by christophebedard** [comment]
Seems like this has been deployed. Thank you @junghans and @drazisil!

**Comment by drazisil** [comment]
Been out dick so forgot to update. Yep.

**Pull request merged**
