### PR TITLE
Add initial Dockerfile

### PR DESCRIPTION
**Pull request by fermayo**
Building the image:
`docker build -t codecov .`

Using it, from within the folder with the coverage file:
`docker run -it -v $(pwd):/app codecov`

### CODE REVIEW

**Comment by stevepeak** [comment]
Hey @fermayo Thank you for the pull. I'm curious what the use case for this is?
Thank you.

**Comment by fermayo** [comment]
* You just need `docker` to run the codecov script, instead of assuming the machine has tools like `curl`, `bash`, `git`, etc. with the versions the script needs.
* If codecov provides an official image for this, it could be versioned controlled, etc. Or at least the user can build its own and know the script that will be executed.
* The script runs in a controlled environment (a container) that has less privileges and access to the host that running it on the master process.

**Comment by stevepeak** [comment]
> You just need docker to run the codecov script, instead of assuming the machine has tools like curl, bash, git, etc. with the versions the script needs.

When executing the docker container could it still access the following data:
- Environment variables
- interact with `git | hg` w/ the project in scope
- read files in project directory

> If codecov provides an official image for this, it could be versioned controlled, etc. Or at least the user can build its own and know the script that will be executed.

👍 

> The script runs in a controlled environment (a container) that has less privileges and access to the host that running it on the master process.

👍

**Comment by jhabdas** [comment]
IMHO Docker probably adds more complexity here than it saves. Is alpine a microcontainer or a full half-gig of Linux?

**Comment by stevepeak** [comment]
@jhabdas I agree about the added complexity. At this time we can not "officially" support a Docker uploading script.

**Pull request closed without merging**
