### PR TITLE
Use maxdepth as part of find

### PR DESCRIPTION
**Pull request by jwillemsen**
See #264

## Purpose
Fix issue #264

## Notable Changes
Are there any changes that need to be called out as particularly tricky or significant?

## Tests and Risks?
Is this covered by existing tests? New ones? If no, why not?

## Update the SHA1SUM file

Also make sure that you update the sha1 hash by running `sha1sum codecov` and updating the SHA1SUM file with the output

### CODE REVIEW

**Comment by haampie** [comment]
Can someone please review & merge this? Ping @drazisil 

This is indeed the correct command. `-depth` is for depth-first traversal and does not expect arguments, `-maxdepth 1` is what is obviously intended.

**Comment by drazisil** [comment]
@haampie please updar rge SHA1SUM 

@thomasrockhu can you review when this is done?

**Comment by haampie** [comment]
@thomasrockhu see #291 if @jwillemsen has not already included the new sha1sum in this pr :)

**Comment by drazisil** [comment]
Thanks, I'm currently OoO and didn't notice you weren't the original author

**Comment by haampie** [comment]
This PR can now be closed since #291 is merged

**Pull request closed without merging**
