### PR TITLE
Store upload data in temporary file rather than in memory

### PR DESCRIPTION
**Pull request by nijel**
With many files the in memory concatenation is really slow, doing that
in file is much faster.

Issue #38 

Please note that this is untested code, so it might needs some adjustments!

### CODE REVIEW

**Comment by nijel** [comment]
I've just tested this on gammu/gammu. So far the test has completed on Travis CI and the script execution went down from 38 seconds to 6 seconds.

Original uploader log: https://travis-ci.org/gammu/gammu/jobs/155249228#L3710
Patched uploader log: https://travis-ci.org/gammu/gammu/jobs/155275749#L3716

I'll also report findings on AppVeyor once the build completes there.

**Comment by stevepeak** [comment]
Awesome job! I'll need to fix the test suite, but overall it looks good.

**Comment by nijel** [comment]
Thanks! 

BTW: The performance boost on AppVeyor seems even bigger (in my case it's about 10 times faster).

**Comment by stevepeak** [comment]
Great news! I'm cleaning up the test suite, but the the all passed with these changes. Great job!

**Pull request merged**
