### PR TITLE
Fixes detection of AppVeyor

### PR DESCRIPTION
**Pull request by jherby2k**
Simple change to fix detection of AppVeyor on Linux.

### CODE REVIEW

**Comment by jherby2k** [comment]
Fixed the test, but I don’t think these tests are passing for anyone right now

**Comment by drazisil** [comment]
@blueyed as a fellow Appveyor user, can I ask you to review that this won't break anything?

**Comment by drazisil** [comment]
Fixes #125

**Comment by drazisil** [comment]
Hi @jherby2k 

I'm sorry this got lost in review. Thank you and merging.

**Pull request merged**
