### PR TITLE
Update CodeBuild CI detection to use CODEBUILD_CI env var

### PR DESCRIPTION
**Pull request by rasarora**
## Purpose
What is the context of this pull request? Why is it being done?
Update CodeBuild CI detection to use CodeBuild's environment variable for CI: CODEBUILD_CI 

## Notable Changes
Are there any changes that need to be called out as particularly tricky or significant?
N/A

## Tests and Risks?
Is this covered by existing tests? New ones? If no, why not?
Yes

## Update the SHA1SUM file

Also make sure that you update the sha1 hash by running `sha1sum codecov` and updating the SHA1SUM file with the output

Updated the SHA1SUM file

### CODE REVIEW

**Comment by rasarora** [comment]
@ibrahim0814 
Hi Ibrahim, Could you please take a look at this pull request? Thanks!

**Comment by drazisil** [comment]
Thank you @rasarora Can I ask you to update the SHA1SUM file again, please?

**Comment by rasarora** [comment]
@drazisil
I synced the branch with the existing codebase and updated the SHA1SUM file

**Comment by drazisil** [comment]
Requested deployment.

**Pull request merged**
