### PR TITLE
Determine why tests are hanging on CircleCI

### PR DESCRIPTION
**Pull request by drazisil**
This is a PR to trigger a build on CircleCI

### CODE REVIEW

**Comment by blueyed** [comment]
JFI: it failed on master already: https://circleci.com/gh/codecov/codecov-bash/708

**Comment by drazisil** [comment]
> JFI: it failed on master already: https://circleci.com/gh/codecov/codecov-bash/708

That was because there was a setting turned off on CircleCI. That's why I made this PR, to fix that.

**Comment by drazisil** [comment]
But why does it have the old broken test data?

**Comment by drazisil** [comment]
No idea why the tests as failing on CircleCI when they pass on Travs

**Pull request closed without merging**
