### PR TITLE
Fix bitbucket repo slug for CodeBuild

### PR DESCRIPTION
**Pull request by rasarora**
## Purpose
What is the context of this pull request? Why is it being done?
Fix bitbucket repo slug for CodeBuild

## Notable Changes
Are there any changes that need to be called out as particularly tricky or significant?
N/A

## Tests and Risks?
Is this covered by existing tests? New ones? If no, why not?
Added new test

## Update the SHA1SUM file

Also make sure that you update the sha1 hash by running `sha1sum codecov` and updating the SHA1SUM file with the output
Updated the SHA1SUM file

### CODE REVIEW

**Comment by rasarora** [comment]
Hi @drazisil, could you please take a look at this pull request? Thanks!

**Comment by drazisil** [comment]
Looks good on mobile, will review tomorrow

**Comment by rasarora** [comment]
okay, thank you!

**Comment by drazisil** [comment]
Deployment requested.

**Comment by rasarora** [comment]
Hi @drazisil, do we know when this change is expected to be deployed?

**Comment by drazisil** [comment]
Off-hand, no. Let me check on Monday.

**Comment by drazisil** [comment]
@rasarora I'm being told today, will update the PR when done.

**Comment by drazisil** [comment]
This has been deployed

**Comment by rasarora** [comment]
Thank you @drazisil

**Pull request merged**
