### PR TITLE
Support pr, job and tag with Drone

### PR DESCRIPTION
**Pull request by fsouza**
Appararently, these variables are available when you run your own Drone.

Source: http://readme.drone.io/usage/variables/

### CODE REVIEW

**Comment by stevepeak** [comment]
Hey @fsouza I'm not seeing these values in the [Drone docs](http://docs.drone.io/env.html). Are these set by default or use defined?

**Comment by fsouza** [comment]
@stevepeak they're set by default only if you're running Drone on-premises. It looks like the public Drone service doesn't set these variables.

**Comment by fsouza** [comment]
Actually, I think this doesn't work, because the on-premises Drone doesn't set the BUILD_URL environment variable. Please hold on, I'll try to come up with a solution that actually works with our Drone setup.

**Comment by fsouza** [comment]
@stevepeak does codecov server try to reach the URL reported by $DRONE_BUILD_URL/$CI_BUILD_URL?

**Comment by stevepeak** [comment]
@fsouza we only use the build url to help redirect the users back to the build from codecov. At this time we do not use it for any other reason.

**Pull request merged**
