### PR TITLE
Deployed Version is a link not an image

### PR DESCRIPTION
**Pull request by szepeviktor**
in README

### CODE REVIEW

**Comment by szepeviktor** [comment]
@drazisil if you are around could you take a look at this?

**Comment by drazisil** [comment]
This was intentional. What do you have in mind, re: an image?

**Comment by szepeviktor** [comment]
This is a link but in Markdown it is written as an image `alt`ű

**Comment by drazisil** [comment]
Oh, right. Yep, that's me failing at Markdown, thought this was an issue, not a PR. 🤦‍♀

**Pull request merged**
