### PR TITLE
Add support for Jenkins Blue Ocean

### LINKED ISSUE #66: Add support for Jenkins Blue Ocean
See codecov/codecov-node/issues/55

### PR DESCRIPTION
**Pull request by rochdev**
closes #66

### CODE REVIEW

**Comment by rochdev** [comment]
Any idea why it fails on CircleCI? It's code that was untouched so it seems like the build was probably already failing.

**Comment by stevepeak** [comment]
@rochdev is this version working in your Jenkins?

**Comment by stevepeak** [comment]
We have implemented this pull's changes in another way recently. However, this could be an outstanding issue: https://github.com/codecov/codecov-bash/commit/fc1edab1aa2cf89eff062e72f7d4cb11ff00d95c

**Comment by stevepeak** [comment]
d

**Comment by rochdev** [comment]
@stevepeak We ended up making a Jenkins helper script to convert the old Jenkins variables to the Blue Ocean ones, so I unfortunately cannot test this at the moment.

From what I can see at a glance it should definitely work. I'll let you know if we face any issues such as the one you mentioned.

**Pull request closed without merging**
