### PR TITLE
Execute gcov once per file with `-execdir`

### LINKED ISSUE #162: new codecov.io/bash script broke my coverage on travis-CI
I've spent much of today upgrading and re-downgrading my compiler versions, test runners, gcov, etc. as my coverage suddenly went from 75% to 44%. First I thought it might have been some issue with my codebase, however I don't think this is the case.

I went into travis, and restarted an old build - this means the build was on the same commit for my project, same travis script etc.. The only possible differences between the builds are: packages available to travis at runtime, and the codecov.io bash script. The old build, from about a month ago, had proper coverage data.

In the restarted build I observed lots of 0% line coverage, and even "no executable lines" from the gcov output which codecov.io's script runs. Whereas on previous builds, it's clear that gcov is producing sensible line coverage numbers.

The version of the codecov script which worked was `0b37652`, and the current version which I'm observing the undesirable behaviour is `8a28df4`. This all seems odd as the former version (which I can only assume refers to a commit hash) is from a year ago, and I can't seem to find the latter.

To be even more sure, I specifically downloaded the file on [this commit](https://raw.githubusercontent.com/codecov/codecov-bash/0b376529f626b50b7d4a9fb734e0e50d28b9b91e/codecov), used it in my travis script, and found it to fix my coverage.

I don't know what has changed under the hood, perhaps something irreversible, but if not I think this should be looked into.

The project in question is a C++17 project built with cmake, make, GCC-7, gtest 1.7.0, gcov-7 (incidentally I found the same behaviour on gcc-8, gtest 1.8.2, and gcov-8).

### LINKED ISSUE #248: macOS always fails for gcov CMake projects
This may be a duplicate of #162.

On macOS `-execdir` and `+` bomb every time with:

```bash
     270 + say '\033[0;90m==>\033[0m Running gcov in /Users/ibeekman/Sandbox/ZstdFortranLib \033[0;90m(disable via -X gcov)\033[0m'
     271 + echo -e '\033[0;90m==>\033[0m Running gcov in /Users/ibeekman/Sandbox/ZstdFortranLib \033[0;90m(disable via -X gcov)\033[0m'
     272 ==> Running gcov in /Users/ibeekman/Sandbox/ZstdFortranLib (disable via -X gcov)
     273 + bash -c 'find /Users/ibeekman/Sandbox/ZstdFortranLib -type f -name '\''*.gcno'\''  -not -path '\''./bower_components/**'\'' -not -path '\''./node_modules/**'\'' -not -path '\''./vendor/**'\'' -not -path '\''*/extern/*'\'' -     273 not -path '\''*/test/*'\'' -execdir gcov-9 -pb  {} +'
     274 testing_interface.F90.gcno:cannot open notes file
     275 testing_interface.F90.gcda:cannot open data file, assuming not executed
     276 testing_implementation.F90.gcno:cannot open notes file
     277 testing_implementation.F90.gcda:cannot open data file, assuming not executed
     278 c_interfaces.F90.gcno:cannot open notes file
     279 c_interfaces.F90.gcda:cannot open data file, assuming not executed
     280 strings.F90.gcno:cannot open notes file
     281 strings.F90.gcda:cannot open data file, assuming not executed
     282 testing.F90.gcno:cannot open notes file
     283 testing.F90.gcda:cannot open data file, assuming not executed
     284 error_stack.F90.gcno:cannot open notes file
     285 error_stack.F90.gcda:cannot open data file, assuming not executed
     286 env_interface.F90.gcno:cannot open notes file
     287 env_interface.F90.gcda:cannot open data file, assuming not executed
     288 get_terminal_size.c.gcno:cannot open notes file
     289 get_terminal_size.c.gcda:cannot open data file, assuming not executed
     290 is_a_tty.c.gcno:cannot open notes file
     291 is_a_tty.c.gcda:cannot open data file, assuming not executed
```

Switching to `+` to `\;` results in finding the files and generating `*.gcov`:

```bash
$ bash -c 'find /Users/ibeekman/Sandbox/ZstdFortranLib -type f \
    -name '\''*.gcno'\''  -not -path '\''./bower_components/**'\'' \
    -not -path '\''./node_modules/**'\'' -not -path '\''./vendor/**'\'' \
    -not -path '\''*/extern/*'\'' -not -path '\''*/test/*'\'' \
    -execdir gcov-9 -pb  "{}" \;'

testing_interface.F90.gcno:no functions found
testing_interface.F90.gcda:cannot open data file, assuming not executed
File '/Users/ibeekman/Sandbox/ZstdFortranLib/generated/GNU/testing_implementation.F90'
Lines executed:96.05% of 152
Branches executed:100.00% of 30
Taken at least once:63.33% of 30
Calls executed:50.79% of 63
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#generated#GNU#testing_implementation.F90.gcov'

c_interfaces.F90.gcno:no functions found
c_interfaces.F90.gcda:cannot open data file, assuming not executed
File '/Users/ibeekman/Sandbox/ZstdFortranLib/generated/GNU/strings.F90'
Lines executed:99.32% of 881
Branches executed:90.72% of 2478
Taken at least once:47.70% of 2478
Calls executed:45.62% of 651
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#generated#GNU#strings.F90.gcov'

File '/Users/ibeekman/Sandbox/ZstdFortranLib/generated/GNU/testing.F90'
Lines executed:0.00% of 1
No branches
No calls
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#generated#GNU#testing.F90.gcov'

File '/Users/ibeekman/Sandbox/ZstdFortranLib/generated/GNU/error_stack.F90'
Lines executed:87.50% of 16
Branches executed:100.00% of 10
Taken at least once:70.00% of 10
Calls executed:93.75% of 16
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#generated#GNU#error_stack.F90.gcov'

File '/Users/ibeekman/Sandbox/ZstdFortranLib/generated/GNU/env_interface.F90'
Lines executed:84.13% of 63
Branches executed:81.94% of 155
Taken at least once:47.10% of 155
Calls executed:80.65% of 93
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#generated#GNU#env_interface.F90.gcov'

File '/Users/ibeekman/Sandbox/ZstdFortranLib/src/c_interfaces/get_terminal_size.c'
Lines executed:100.00% of 8
No branches
Calls executed:100.00% of 2
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#src#c_interfaces#get_terminal_size.c.gcov'

File '/Users/ibeekman/Sandbox/ZstdFortranLib/src/c_interfaces/is_a_tty.c'
Lines executed:100.00% of 2
No branches
Calls executed:100.00% of 2
Creating '#Users#ibeekman#Sandbox#ZstdFortranLib#src#c_interfaces#is_a_tty.c.gcov'
```

A fix for this would be really nice.

### PR DESCRIPTION
**Pull request by zbeekman**
- Fixes #248
- Fixes #162
- Closes #159 (I think this is the correct way to do #159)

## Purpose

Address #248 & #162. Complete failure of codecov.io on macOS and execute gcov once per file.

## Notable Changes
Are there any changes that need to be called out as particularly tricky or significant?

I don't think so

## Tests and Risks?
Is this covered by existing tests? New ones? If no, why not?

I'll need to further investigate

## Update the SHA1SUM file

Also make sure that you update the sha1 hash by running `sha1sum codecov` and updating the SHA1SUM file with the output
Change the `codecov` to `-` in the file before committing so it can be compared against the server file 

Done

### CODE REVIEW

**Comment by zbeekman** [comment]
Seems like gcov test is disabled, not sure why

**Comment by drazisil** [comment]
I would love if someone with more bash experience then I could review this :)

**Comment by zbeekman** [comment]
@drazisil anything I can do to help?

This is not really about bash, but, rather about the `find` command.

The only change here is to switch the termination of the `-execdir` flag to `\;` instead of `+`. What this is doing is changing it so that the `gcov` command is being run inside a directory with a matching `.gcno` but instead of running the `gcov` command once per directory with a match and passing every file in that directory as arguments, it is running it once per file. So this will cause processing of coverage info to slow down, since gcov is being invoked once per file instead of once per directory with matching files, but it fixes problems people have been reporting (multiple users report issues in #162 in addition to my #248). In #162 users are working around this problem by reverting to older versions of the bash coverage collection/upload script that was present before someone made this change (either `\;` to `+` or, perhaps, `-exec` to `-execdir`).

This could be a problem that's specific to macOS or a bug in find or gcov, I'm not sure. But, basically, the switch from `-exec` to `-execdir`, both ending the command with the "call once, pass multiple files" `+` command terminator triggered these issues. Using `-execdir` over `-exec` is preferable because, otherwise, `find` runs the command from the directory in which `find` was invoked causing the `gcov` outputs to be dumped there. This can, at least on some OSes like macOS, cause codecov to get confused about which file the coverage reports correspond to.

**Comment by drazisil** [comment]
That was very helpful, thanks!

**Pull request merged**
