### PR TITLE
fix: allow absolute paths for codecov.yml

### PR DESCRIPTION
**Pull request by joscha**
This fixes the bash script to not assume that any file passed via `-y` is relative to the repo root.

When dynamically generating the yml to be read by codecov we are currently using a temporary file created by `mktemp` which is not beneath the repo root.

cc @e-e-e

### CODE REVIEW

**Comment by joscha** [comment]
CI failures also seem to appear on `master` and unrelated?

**Comment by e-e-e** [comment]
This PR closes #149.

**Comment by joscha** [comment]
@stevepeak any chance to get this in?

**Comment by focom** [comment]
Would be great to have this!

**Comment by drazisil** [comment]
@joscha Is it possible for you to merge master into this branch? I tried myself, but since I don't have access to your branch, things didn't go so well.

**Comment by joscha** [comment]
@drazisil done

**Comment by drazisil** [comment]
@joscha I forgot to mention you need to update the SHA1SUM file too, sorry.

**Comment by joscha** [comment]
> @joscha I forgot to mention you need to update the SHA1SUM file too, sorry.

done

**Comment by drazisil** [comment]
Deployment requested

**Comment by joshua0308** [comment]
@joscha 
I am trying to dynamically generate `codecov.yml` file during CI, but couldn't get it to function properly at work. What you are describing sounds a lot like what I've been trying to do for the past few days. Would you mind sharing an example how to dynamically generate `codecov.yml` and pass it to `Codecov`? 

@drazisil 
Correct me if I am wrong but I was under the impression that dynamically editing `codecov.yml` from CI does not work because `Codecov` uses the yml committed to `git` in the backend. Any help or guidance would be very much appreciated. Thank you!

**Comment by joscha** [comment]
> @joscha
> I am trying to dynamically generate `codecov.yml` file during CI, but couldn't get it to function properly at work. What you are describing sounds a lot like what I've been trying to do for the past few days. Would you mind sharing an example how to dynamically generate `codecov.yml` and pass it to `Codecov`?

Sorry, it didn't work back then because of this bug, so we have switched to https://github.com/joscha/codecov-buildkite-plugin a while back.

**Pull request merged**
