### PR TITLE
Feature/bitbucket env

### LINKED ISSUE #223: Bitbucket Pipelines Support
Something went wrong with https://github.com/codecov/codecov-bash/pull/135 and now the `env` file does not contain a check for bitbucket.

I can create a PR if interested.

### PR DESCRIPTION
**Pull request by KajdeMunter**
## Purpose
Fixes #223 

I also added the `BITBUCKET_COMMIT` environment variable.

## Tests and Risks?
Tests were already in place but added `BITBUCKET_COMMIT` variable.

### CODE REVIEW

**Comment by KajdeMunter** [comment]
This might not be the right place for this; but even with these changes I can't get it to work correctly. 

Codecov tells commits are `Waiting for CI to complete. Please review report with caution, it may change`. I am running the bash script inside docker in a Bitbucket Pipeline.

**Comment by Slamdunk** [comment]
Hi, in a repo on Bitbucket I hade no issue until 950b21e included.
Starting from 4983e44 I repetedly get the following error.

Full diff https://github.com/codecov/codecov-bash/compare/950b21e...4983e44 tells this is the only PR involving Bitbucket.

```
+ codecov -f tmp/clover.xml
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-20191120-4983e44
==> Bitbucket detected.
    project root: .
--> token set from env
    Yaml found at: codecov.yml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + tmp/clover.xml bytes=2342173
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Gzipping contents
==> Uploading reports
    url: https://codecov.io
    query: branch=OMISSIS&commit=07816c12f12b&build=737&build_url=&name=&tag=&slug=OMISSIS%2FOMISSIS&service=bitbucket&flags=&pr=149&job=737
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=OMISSIS&commit=07816c12f12b&build=737&build_url=&name=&tag=&slug=OMISSIS%2FOMISSIS&service=bitbucket&flags=&pr=149&job=737
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=OMISSIS&commit=07816c12f12b&build=737&build_url=&name=&tag=&slug=OMISSIS%2FOMISSIS&service=bitbucket&flags=&pr=149&job=737
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=OMISSIS&commit=07816c12f12b&build=737&build_url=&name=&tag=&slug=OMISSIS%2FOMISSIS&service=bitbucket&flags=&pr=149&job=737
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Pinging Codecov
https://codecov.io/upload/v4?package=bash-20191120-4983e44&token=secret&branch=OMISSIS&commit=07816c12f12b&build=737&build_url=&name=&tag=&slug=OMISSIS%2FOMISSIS&service=bitbucket&flags=&pr=149&job=737
    -> Uploading
    X> Failed to upload
    -> Sleeping for 30s and trying again...
    -> Uploading to Codecov
    HTTP 400
commit must match pattern ^\d+:\w{12}|\w{40}$
```

The `bitbucket-pipelines.yml` is pretty straightforward:
```
customdefinitions:
  - phptest: &phptest
      name: PHP Tests
      image: zoeslam/docker-php:7.3
      script:
        - composer install --ansi --classmap-authoritative
        - vendor/bin/phpunit --color=always --configuration=cc.xml --coverage-clover=tmp/clover.xml
        - codecov -f tmp/clover.xml

pipelines:
  pull-requests:
    '**':
      - step: *phptest
  branches:
    master:
      - step: *phptest
```

And this is the Dockerfile for the base image: https://github.com/Slamdunk/docker-php/blob/master/7.3.Dockerfile

Any guess on what could be happening?

**Comment by KajdeMunter** [comment]
What is the value of your `BITBUCKET_COMMIT` environment variable?

**Comment by Slamdunk** [comment]
This is (part of) `printenv` (with OMISSIS on sensitive data):

```
BITBUCKET_BRANCH=codecov_debug
BITBUCKET_BUILD_NUMBER=751
BITBUCKET_CLONE_DIR=/opt/atlassian/pipelines/agent/build
BITBUCKET_COMMIT=3fffce06e9e2
BITBUCKET_DOCKER_HOST_INTERNAL=10.36.219.180
BITBUCKET_GIT_HTTP_ORIGIN=http://bitbucket.org/OMISSIS/OMISSIS
BITBUCKET_GIT_SSH_ORIGIN=git@bitbucket.org:OMISSIS/OMISSIS.git
BITBUCKET_PARALLEL_STEP=0
BITBUCKET_PARALLEL_STEP_COUNT=1
BITBUCKET_PROJECT_KEY=OMISSIS
BITBUCKET_PROJECT_UUID={OMISSISX-14fc-4a36-8d98-0361d16ef224}
BITBUCKET_PR_DESTINATION_BRANCH=master
BITBUCKET_PR_DESTINATION_COMMIT=fca79568d3ec
BITBUCKET_PR_ID=153
BITBUCKET_REPO_FULL_NAME=OMISSIS/OMISSIS
BITBUCKET_REPO_IS_PRIVATE=true
BITBUCKET_REPO_OWNER=OMISSIS
BITBUCKET_REPO_OWNER_UUID={OMISSISX-a82e-4918-91f7-d98d72d91b7f}
BITBUCKET_REPO_SLUG=OMISSIS
BITBUCKET_REPO_UUID={OMISSISX-d50c-48d5-aec1-b4ab9be0895f}
BITBUCKET_STEP_RUN_NUMBER=1
BITBUCKET_STEP_TRIGGERER_UUID={OMISSISX-eeee-43cd-867e-56b09dbfc444}
BITBUCKET_WORKSPACE=OMISSIS
CI=true
```

**Comment by KajdeMunter** [comment]
Hmm.. Weird, I'm pretty sure `BITBUCKET_COMMIT` should be the full commit hash. The error message is correct, as `^\d+:\w{12}|\w{40}$` does not match `3fffce06e9e2` because of the `\d+:` part of the regex.

**Comment by Slamdunk** [comment]
It seems all the Pipeling is using this short version, these are the first lines of the Build step:
```
+ umask 000

+ GIT_LFS_SKIP_SMUDGE=1 git clone --branch="codecov_debug" https://x-token-auth:$REPOSITORY_OAUTH_ACCESS_TOKEN@bitbucket.org/$BITBUCKET_REPO_FULL_NAME.git $BUILD_DIR
Cloning into '/opt/atlassian/pipelines/agent/build'...

+ git reset --hard 3fffce06e9e2
HEAD is now at 3fffce06 Debug for Codecov
```
What can we do about this?

**Comment by KajdeMunter** [comment]
Where did you run your `printenv`? Inside the container or the pipeline?

**Comment by Slamdunk** [comment]
Inside the pipeline

**Comment by KajdeMunter** [comment]
Could it be some weird bitbucket bug? https://jira.atlassian.com/browse/BCLOUD-19393

**Comment by drazisil** [comment]
This does look to be the cause. If the env doesn't give us what we need you will need to manually provide it with the `-C` flag.

**Comment by drazisil** [comment]
I've moved this issue to here https://github.com/codecov/codecov-bash/issues/241

Going to close this thread, since this PR is not the cause of the issue.

**Pull request merged**
